### ISSUE TITLE
PHP Baseline adding information to l5-swagger (laravel)

### ISSUE THREAD

**Issue by dedmen7** [isaaceindhoven/php-code-sniffer-baseliner#2]
When using the PHPCS baseliner, additions are added in an annotation of the swagger documentation. This ensures that l5-swagger cannot generate documentation.

In the code below there is an example where te baseliner adds an ignore to the swagger documentation. If the swagger code would be generated for testing it would give an error because it cant compile the baseliner ignore.

Is it possible that when the baseliner is used the swagger documentation is skipped so that no compile errors can occur?

Here is an example of the annotations in the code:
 
* @OA\ Property( 
  * property = "order_lines[0][no]", 
  * type = "string", 
  * example = "1211-0110", 
  * phpcs: ignore SlevomatCodingStandard.Files.LineLength.LineTooLong--baseline 
  * description = "Order item0article number. To add more order lines, replace[0]with the correct incremental number", 
*), 
* @OA\ Property( 
 * property = "order_lines[0][vpe]", 
 * type = "integer", 
 * example = 1, 
 * phpcs: ignore SlevomatCodingStandard.Files.LineLength.LineTooLong--baseline 
 * description = "Order item0packing unit. To add more order lines, replace[0]with the correct incremental number",
*),

**Comment by jeroennoten** [comment]
Hi @dedmen7, thanks for reporting this issue. This has fixed in version 2.1.1. Could you please verify this and close this issue if the problem has been resolved?
